version: '3'

services:
    laravel-app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - DB_CONNECTION=sqlite
